export const GO_HOME = 'GO_HOME';
export const GO_MARKET = 'GO_MARKET';
export const GO_MARKET_CATEGORY = 'GO_MARKET_CATEGORY';
export const GO_MARKET_CATEGORY_SUBCATEGORY = 'GO_MARKET_CATEGORY_SUBCATEGORY';
