export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCEEDED = 'GET_ITEMS_SUCCEEDED';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';
export const GET_FEATURED_REQUEST = 'GET_FEATURED_REQUEST';
export const GET_FEATURED_SUCCEEDED = 'GET_FEATURED_SUCCEEDED';
export const GET_FEATURED_FAILED = 'GET_FEATURED_FAILED';
