export const CLOSE_ASIDE = 'CLOSE_ASIDE';
export const OPEN_ASIDE = 'OPEN_ASIDE';
export const EXPAND_CATEGORY = 'EXPAND_CATEGORY';
export const COLLAPSE_CATEGORY = 'COLLAPSE_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';