export const CLOSE_ASIDE = 'CLOSE_ASIDE';
export const OPEN_ASIDE = 'OPEN_ASIDE';
export const EXPAND_CATEGORY = 'EXPAND_CATEGORY';
export const COLLAPSE_CATEGORY = 'COLLAPSE_CATEGORY';
export const CHANGE_SUBCATEGORY = 'CHANGE_SUBCATEGORY';
export const SET_MARKET = 'SET_MARKET';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SUBCATEGORY = 'SET_SUBCATEGORY';