export const CLOSE_CATEGORIES = 'CLOSE_CATEGORIES';
export const EXPAND_CATEGORY = 'EXPAND_CATEGORY';
export const COLLAPSE_CATEGORY = 'COLLAPSE_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';